spring:
  datasource:
    url: jdbc:mysql://localhost:3360/sfg_prod
    username: sfg_prod_user
    password: guru
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    show-sql: false